### ISSUE TITLE
Faute d'orthographe

### ISSUE THREAD

**Issue by metafab** [Svelte-Society-Fr/svelte#139]
Sur [https://kit.sveltefr.dev/docs/configuration#csp](https://kit.sveltefr.dev/docs/configuration#csp) :

> "les endroits depuis lesquels les ressourcent peuvent être téléchargées."

→ " les endroits depuis lesquels les ressources peuvent être téléchargées."

**Comment by metafab** [comment]
Oups, ce ticket est à déplacer dans Kit.

**Comment by bleucitron** [comment]
Fixed
